stages:
  - build

default:
  image: node:18.17.1-buster

build:
  stage: build
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
  script:
    - pnpm install
    - pnpm run build
    - tar -czf quizbot.tar.gz -C "dist" .
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file quizbot.tar.gz "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/quizbot/${CI_COMMIT_SHORT_SHA}/quizbot.tar.gz"'
  only:
    - main