# Define the Docker image to use for the entire pipeline.
image: node:latest

# Define the stages of your pipeline.
stages:
- build
- deploy

# Define jobs for each stage.
build:
  stage: build
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
  script:
  - pnpm install # install dependencies
  - echo "Building your project..."
  - pnpm install
  - pnpm run build
  - cp -r dist/* public/
  artifacts:
    paths:
      - public
  only:
    - main

pages:
  stage: deploy
  script:
  - echo "Deploying your application..."
  artifacts:
    paths:
      - public

  only:
    - main